---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-port-check-privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: port-check
  name: port-check
  namespace: oof-port-check-privileged
spec:
  selector:
    matchLabels:
      app: port-check
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: port-check
    spec:
      containers:
        - name: port-check
          image: ghcr.io/peschmae/oof-test-workload:latest
          command:
            - "bind_to_port"
            - "80"
          securityContext: {}
---
apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: port-check-privileged
  namespace: oof-port-check-privileged
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: port-check
  baselineDuration: 1m