---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-run-as-root
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: root-check
  name: root-check
  namespace: oof-run-as-root
spec:
  selector:
    matchLabels:
      app: root-check
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: root-check
    spec:
      containers:
        - name: root-check
          image: ghcr.io/peschmae/oof-test-workload:latest
          command:
            - must_run_as_root
          securityContext: {}
---
apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: root-check
  namespace: oof-run-as-root
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root-check
  baselineDuration: 1m