---
apiVersion: v1
kind: Namespace
metadata:
  name: oof-write-fs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: write-fs
  name: write-fs
  namespace: oof-write-fs
spec:
  selector:
    matchLabels:
      app: write-fs
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: write-fs
    spec:
      containers:
        - name: write-fs
          image: ghcr.io/peschmae/oof-test-workload:latest
          command:
            - "write_to_dir"
            - "/tmp/"
          securityContext: {}
---
apiVersion: checks.funk.fhnw.ch/v1alpha1
kind: WorkloadHardeningCheck
metadata:
  name: write-fs
  namespace: oof-write-fs
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: write-fs
  baselineDuration: 1m