#! /bin/bash

set -e # Exit on error
set -u # Treat unset variables as an error
set -o pipefail # Fail on any command in a pipeline that fails


# This script checks if the user is root and exits with an error if not.
if [ "$(id -u)" -ne 0 ]; then
  echo "[$( date --rfc-3339=s)] Error: This script must be run as root."
  exit 1
fi

echo "[$( date --rfc-3339=s)] Running as root user."
sleep 600 # Sleep for 10 minutes to keep the script running